pass:
  build: pass
  environment:
    ADMIN: sa
    ADMIN_PASS: 1
  ports:
    - '2201:22'

key:
  build: key
  environment:
    ADMIN: sa
  ports:
    - '2202:22'

authykey:
  build: authykey
  environment:
    AUTHY_API_KEY: ${AUTHY_API_KEY}
    ADMIN_LIST: ${ADMIN_LIST}
    # template for it is "unixUserName:email:countrycode:phoneNumber unixUserName:email:countrycode:phoneNumber"
  ports:
    - '2203:22'

authypass:
  build: authypass
  environment:
    AUTHY_API_KEY: ${AUTHY_API_KEY}
    ADMIN_LIST: ${ADMIN_LIST}
    # template for it is "unixUserName:email:countrycode:phoneNumber unixUserName:email:countrycode:phoneNumber"
  ports:
    - '2204:22'
