pass:
  build: pass
  environment:
    ADMIN: sa
    ADMIN_PASS: 1
  ports:
    - '2201:22'

key:
  build: key
  environment:
    ADMIN: sa
  ports:
    - '2202:22'

authykey:
  build: authykey
  environment:
    ADMIN: sa
    AUTHY_API_KEY: ${AUTHY_API_KEY}
    AUTHY_PHONE: ${AUTHY_PHONE}
    AUTHY_EMAIL: ${AUTHY_EMAIL}
    AUTHY_CONTRY_CODE: ${AUTHY_CONTRY_CODE}
  ports:
    - '2203:22'

authypass:
  build: authypass
  environment:
    ADMIN: sa
    AUTHY_API_KEY: zhDa85XgGi61HTOG1zJSZmn0dBZN8q6w
  ports:
    - '2204:22'
